/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemPerpustakaan;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Toshiba
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
     Connection con = null;
    Statement stmn = null;
    ResultSet rs = null;
    PreparedStatement psmt = null;
    public Menu() {
        initComponents();
        
    }
static String NIM;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuUtama1 = new Gambar.MenuUtama();
        BtnKembali = new TextFiels.TextButton();
        BtnPinjam = new TextFiels.TextButton();
        TxtNama = new javax.swing.JTextField();
        TxtNIM = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        BtnKembali.setText("textButton1");
        BtnKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnKembaliMouseClicked(evt);
            }
        });
        BtnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKembaliActionPerformed(evt);
            }
        });

        BtnPinjam.setText("textButton1");
        BtnPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPinjamActionPerformed(evt);
            }
        });

        TxtNama.setBackground(new java.awt.Color(225, 225, 225));
        TxtNama.setText("Masukan Nama");
        TxtNama.setBorder(null);
        TxtNama.setCaretColor(new java.awt.Color(225, 225, 225));
        TxtNama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtNamaMouseClicked(evt);
            }
        });
        TxtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaActionPerformed(evt);
            }
        });

        TxtNIM.setBackground(new java.awt.Color(225, 225, 225));
        TxtNIM.setText("Masukan NIM");
        TxtNIM.setBorder(null);
        TxtNIM.setCaretColor(new java.awt.Color(225, 225, 225));
        TxtNIM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtNIMMouseClicked(evt);
            }
        });
        TxtNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNIMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuUtama1Layout = new javax.swing.GroupLayout(menuUtama1);
        menuUtama1.setLayout(menuUtama1Layout);
        menuUtama1Layout.setHorizontalGroup(
            menuUtama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuUtama1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(menuUtama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addComponent(TxtNIM))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuUtama1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuUtama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(128, 128, 128))
        );
        menuUtama1Layout.setVerticalGroup(
            menuUtama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuUtama1Layout.createSequentialGroup()
                .addContainerGap(272, Short.MAX_VALUE)
                .addComponent(TxtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(TxtNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(BtnPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuUtama1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuUtama1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnKembaliMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnKembaliMouseClicked

    private void BtnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKembaliActionPerformed
            Pengembalian a = new Pengembalian();
            a.setVisible(true);
            a.dataTextArea();
    }//GEN-LAST:event_BtnKembaliActionPerformed

    private void BtnPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPinjamActionPerformed
             Peminjaman a = new Peminjaman();
             a.setVisible(true);
    }//GEN-LAST:event_BtnPinjamActionPerformed

    private void TxtNamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtNamaMouseClicked
        TxtNama.setText("");
    }//GEN-LAST:event_TxtNamaMouseClicked

    private void TxtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNamaActionPerformed

    private void TxtNIMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtNIMMouseClicked
        TxtNIM.setText("");
    }//GEN-LAST:event_TxtNIMMouseClicked

    private void TxtNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNIMActionPerformed
        String CocokanNama="";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String url, user, password;
                url = "jdbc:mysql://localhost:3306/databuku"; //alamat DB
                user = "root";
                password = "";
                con = (Connection) DriverManager.getConnection(url, user, password);
                stmn = (Statement) con.createStatement();
                NIM=TxtNIM.getText().toString();
                String SQL = "SELECT * FROM mahasiswa WHERE NIM='"+TxtNIM.getText().toString()+"'";
                rs = stmn.executeQuery(SQL);
                while(rs.next()){
                    CocokanNama = rs.getString("Nama");
                }
                TxtNama.setText(CocokanNama);
                stmn.close();
                con.close();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Koneksi Gagal! " + e);
        }
    }//GEN-LAST:event_TxtNIMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    public String getNIM() {
        return NIM;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private TextFiels.TextButton BtnKembali;
    private TextFiels.TextButton BtnPinjam;
    private javax.swing.JTextField TxtNIM;
    private javax.swing.JTextField TxtNama;
    private Gambar.MenuUtama menuUtama1;
    // End of variables declaration//GEN-END:variables
}
