
import javax.swing.table.DefaultTableModel;
import java.sql.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author R-PC
 */
public class ListPenghuni extends javax.swing.JFrame {

    /**
     * Creates new form ListPenghuni
     * 
     */
    DefaultTableModel D = new DefaultTableModel();
    String nama,id,alamat,hp,kamar,lamaSewa,harga,dari,sampai;
    Koneksi koneksi = new Koneksi();
    int i=1;
    public ListPenghuni() {
        try{
        initComponents();
        koneksi.data();
        koneksi.statement = koneksi.connection.createStatement();
            String sq = "select * from tdatakost";
            koneksi.result = koneksi.statement.executeQuery(sq);
            D.addColumn("No");
            D.addColumn("Nama");
            D.addColumn("ID");
            D.addColumn("No.HP");
            D.addColumn("Alamat");
            D.addColumn("Tipe Kamar");
            D.addColumn("Lama Sewa");
            D.addColumn("Dari");
            D.addColumn("Sampai");
            D.addColumn("Harga");
            
            while(koneksi.result.next()){
                nama = koneksi.result.getString(1);
                id = koneksi.result.getString(2);
                hp = koneksi.result.getString(3);
                alamat = koneksi.result.getString(4);
                kamar = koneksi.result.getString(5);
                lamaSewa = koneksi.result.getString(6);
                dari = koneksi.result.getString(7);
                sampai = koneksi.result.getString(8);
                harga = koneksi.result.getString(9);
                String[] tampil = {""+i++,nama,id,hp,alamat,kamar,lamaSewa,dari,sampai,harga};
                D.addRow(tampil);
                tabel.setModel(D);
                
            }
            tabel.getColumnModel().getColumn(0).setPreferredWidth(30);
            tabel.getColumnModel().getColumn(1).setPreferredWidth(100);
            tabel.getColumnModel().getColumn(2).setPreferredWidth(80);
            tabel.getColumnModel().getColumn(3).setPreferredWidth(80);
            tabel.getColumnModel().getColumn(4).setPreferredWidth(100);
            tabel.getColumnModel().getColumn(5).setPreferredWidth(100);
            tabel.getColumnModel().getColumn(6).setPreferredWidth(100);
            tabel.getColumnModel().getColumn(7).setPreferredWidth(100);
            tabel.getColumnModel().getColumn(8).setPreferredWidth(100);
            tabel.getColumnModel().getColumn(9).setPreferredWidth(110);
            this.setLocationRelativeTo(null);
        }
        catch(Exception e){
            System.out.println(e);
        }
    }
    
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "ID", "No. HP", "Alamat", "Tipe Kamar", "Lama Sewa", "Dari", "Sampai", "Harga"
            }
        ));
        tabel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tabelComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DATA PENGHUNI KOST");

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(back)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(425, 425, 425)
                        .addComponent(jLabel1)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(back)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabelComponentShown
        tabel.setModel(D);
    }//GEN-LAST:event_tabelComponentShown

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Scene1.s.show();
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListPenghuni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListPenghuni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListPenghuni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListPenghuni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListPenghuni().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
