
import javax.swing.JOptionPane;
import java.sql.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author R-PC
 */
public class Scene3 extends javax.swing.JFrame {

    /**
     * Creates new form Scene3_DaftarNama
     */static String nama,id,alamat,hp,kamar,lamaSewa,harga,dari,sampai;
     static int reguler,vip,vvip;
    Koneksi koneksi = new Koneksi();
    public Scene3() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public void updateData(){
        try {
            koneksi.data();
            koneksi.statement = koneksi.connection.createStatement();
            String sq = "select * from tstatus";
            koneksi.result = koneksi.statement.executeQuery(sq);
            if(koneksi.result.next()){
                reguler = Integer.parseInt(koneksi.result.getString(1));
                vip = Integer.parseInt(koneksi.result.getString(2));
                vvip = Integer.parseInt(koneksi.result.getString(3));
            }
            koneksi.statement.executeUpdate("insert into tdatakost values("
                                            +"'"+nama+"',"
                                            +"'"+id+"',"
                                            +"'"+hp+"',"
                                            +"'"+alamat+"',"
                                            +"'"+kamar+"',"
                                            +"'"+lamaSewa+"',"
                                            +"'"+dari+"',"
                                            +"'"+sampai+"',"
                                            +"'"+harga+"')");
            if(kamar.equals("REGULER")){
                reguler-=1;
                String rg = reguler+"";
                String sql = "update tstatus set reguler='"+rg+"'";
                koneksi.statement.executeUpdate(sql);
            }
            else if(kamar.equals("VIP")){
                vip-=1;
                String vp = vip+"";
                String sql = "update tstatus set vip='"+vp+"'";
                koneksi.statement.executeUpdate(sql);
            }
            else{
                vvip-=1;
                String vvp = vvip+"";
                String sql = "update tstatus set vvip='"+vvp+"'";
                koneksi.statement.executeUpdate(sql);
                
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bHome = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        bSignup = new javax.swing.JButton();
        tNama = new javax.swing.JTextField();
        tNomorid = new javax.swing.JTextField();
        tAlamat = new javax.swing.JTextField();
        tNomorhp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DATA DIRI");

        jLabel2.setText("Nama:");

        jLabel3.setText("No. ID:");

        jLabel4.setText("Alamat:");

        jLabel5.setText("No. HP:");

        bHome.setText("HOME");
        bHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHomeActionPerformed(evt);
            }
        });

        bCancel.setText("CANCEL");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        bSignup.setText("SIGN UP");
        bSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSignupActionPerformed(evt);
            }
        });

        tNama.setText(" ");

        tNomorid.setText(" ");
        tNomorid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNomoridActionPerformed(evt);
            }
        });

        tAlamat.setText(" ");

        tNomorhp.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bCancel)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 9, Short.MAX_VALUE)
                                .addComponent(bHome)
                                .addGap(57, 57, 57)
                                .addComponent(bSignup))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tNama, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(tNomorid)
                            .addComponent(tAlamat)
                            .addComponent(tNomorhp))
                        .addGap(9, 9, 9)))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tNomorid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tNomorhp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bHome)
                    .addComponent(bSignup)
                    .addComponent(bCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int t = 0,b=0;
    private void bSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSignupActionPerformed
       if(tNama.getText().equals(" ")||tAlamat.getText().equals(" ")||tNomorid.getText().equals(" ")||tNomorhp.getText().equals(" ")){
           JOptionPane.showMessageDialog(null, "Masih ada data yang kosong!");
       }
       else{
            int reply= JOptionPane.showConfirmDialog(null, "Apakah data anda sudah benar?", "Peringatan", JOptionPane.YES_NO_OPTION);
        if(reply==JOptionPane.YES_OPTION){
        nama = tNama.getText();
        id = tNomorid.getText();
        alamat = tAlamat.getText();
        hp = tNomorhp.getText();
        kamar = Scene2.kamar;
        lamaSewa = SceneHarga.lamasewa;
        dari = SceneHarga.tgl+" "+SceneHarga.month[SceneHarga.bulan-1]+" "+SceneHarga.tahun;
        t=(SceneHarga.bulan+SceneHarga.index)/12;
        sampai = SceneHarga.tgl+" "+SceneHarga.month[((SceneHarga.bulan+SceneHarga.index)%12)-1]+" "+(SceneHarga.tahun+t);
        harga = SceneHarga.harga1;
        new SceneDisplay().show();
        updateData();
        this.dispose();
        }
        else{
            
            
        }
       }
    }//GEN-LAST:event_bSignupActionPerformed

    private void tNomoridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNomoridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNomoridActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        Scene2.sceneharga.show();
        this.dispose();
    }//GEN-LAST:event_bCancelActionPerformed

    private void bHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHomeActionPerformed
        Scene1.s.show();
        this.dispose();
    }//GEN-LAST:event_bHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scene3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scene3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scene3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scene3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scene3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bHome;
    private javax.swing.JButton bSignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tAlamat;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tNomorhp;
    private javax.swing.JTextField tNomorid;
    // End of variables declaration//GEN-END:variables
}
