
import java.awt.event.ItemEvent;
import javax.swing.JCheckBox;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author R-PC
 */
public class Scene2 extends javax.swing.JFrame {

    /**
     * Creates new form Scene2
     */

    static String kamar;
    //Scene1 scene = new Scene1();
    Reguler reg = new Reguler();
    VIP vip1 = new VIP();
    VVIP vvip1 = new VVIP();
    boolean ac,tv,airpanas;
    static SceneHarga sceneharga;
    public Scene2() {
        initComponents();
    }
     public Scene2(String s) { 
         this.kamar=s;
        initComponents();
        judul.setText(s);
        if (s.equals("REGULER")) {
            Lukuran.setText(reg.ukuran());
            LFasilitas1.setText(reg.lemari());
            LFasilitas2.setText(reg.kasur());
            LFasilitas3.setText(reg.meja());
            LFasilitas4.setText(reg.wifi());
            LFasilitas5.setText(reg.kmluar());
            LFasilitas6.setText("");
            Tambahan1.setText("AC");
            Tambahan2.setText("TV");
            Tambahan3.setVisible(false);
        }
        else if(s.equals("VIP")) {
            Lukuran.setText(vip1.ukuran());
            LFasilitas1.setText(vip1.lemari());
            LFasilitas2.setText(vip1.kasur());
            LFasilitas3.setText(vip1.meja());
            LFasilitas4.setText(vip1.wifi());
            LFasilitas5.setText(vip1.kmdalam());
            LFasilitas6.setText("");
            Tambahan1.setText("AC");
            Tambahan2.setText("TV");
            Tambahan3.setText("Air Panas");
        }
        else {
            Lukuran.setText(vvip1.ukuran());
            LFasilitas1.setText(vvip1.lemari());
            LFasilitas2.setText(vvip1.kasur());
            LFasilitas3.setText(vvip1.meja());
            LFasilitas4.setText(vvip1.wifi());
            LFasilitas5.setText(vvip1.kmluar());
            LFasilitas6.setText(vvip1.ac());
            Tambahan1.setText("TV");
            Tambahan2.setText("Air Panas");
            Tambahan3.setVisible(false);
        }
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judul = new javax.swing.JLabel();
        lUkuran = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Lukuran = new javax.swing.JLabel();
        LFasilitas1 = new javax.swing.JLabel();
        LFasilitas2 = new javax.swing.JLabel();
        LFasilitas3 = new javax.swing.JLabel();
        LFasilitas4 = new javax.swing.JLabel();
        LFasilitas5 = new javax.swing.JLabel();
        LFasilitas6 = new javax.swing.JLabel();
        Tambahan1 = new javax.swing.JCheckBox();
        Tambahan2 = new javax.swing.JCheckBox();
        Tambahan3 = new javax.swing.JCheckBox();
        BKembali1 = new javax.swing.JButton();
        BNext1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        judul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        judul.setText("REGULER");

        lUkuran.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lUkuran.setText("Ukuran  : ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Fasilitas :");

        Lukuran.setText("jLabel3");

        LFasilitas1.setText("jLabel4");

        LFasilitas2.setText("jLabel5");

        LFasilitas3.setText("jLabel6");

        LFasilitas4.setText("jLabel7");

        LFasilitas5.setText("jLabel8");

        LFasilitas6.setText("jLabel9");

        Tambahan1.setText("jCheckBox1");
        Tambahan1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Tambahan1ItemStateChanged(evt);
            }
        });
        Tambahan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tambahan1ActionPerformed(evt);
            }
        });

        Tambahan2.setText("jCheckBox2");
        Tambahan2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Tambahan2ItemStateChanged(evt);
            }
        });
        Tambahan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tambahan2ActionPerformed(evt);
            }
        });

        Tambahan3.setText("jCheckBox3");
        Tambahan3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Tambahan3ItemStateChanged(evt);
            }
        });
        Tambahan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tambahan3ActionPerformed(evt);
            }
        });

        BKembali1.setText("Kembali");
        BKembali1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKembali1ActionPerformed(evt);
            }
        });

        BNext1.setText("Selanjutnya");
        BNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNext1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Tambahan :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(BKembali1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BNext1)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lUkuran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Tambahan1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Lukuran)
                                    .addComponent(LFasilitas2, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(LFasilitas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LFasilitas5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LFasilitas6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LFasilitas4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LFasilitas3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Tambahan2)
                                .addGap(18, 18, 18)
                                .addComponent(Tambahan3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(82, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lukuran))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LFasilitas1))
                .addGap(1, 1, 1)
                .addComponent(LFasilitas2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LFasilitas3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LFasilitas4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LFasilitas5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LFasilitas6)
                .addGap(11, 11, 11)
                .addComponent(jLabel10)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tambahan1)
                    .addComponent(Tambahan2)
                    .addComponent(Tambahan3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BKembali1)
                    .addComponent(BNext1))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BKembali1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKembali1ActionPerformed
        Scene1.s.show();
        this.dispose();
    }//GEN-LAST:event_BKembali1ActionPerformed

    private void BNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNext1ActionPerformed
        sceneharga=new SceneHarga(judul.getText(),ac,tv,airpanas);
        sceneharga.show();
        this.dispose();
    }//GEN-LAST:event_BNext1ActionPerformed
    Object x;
    private void Tambahan1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Tambahan1ItemStateChanged
       if(Tambahan1.getText().equals("AC")){
           ac=true;
       }
       if(Tambahan1.getText().equals("TV")){
           tv=true;
       }
    }//GEN-LAST:event_Tambahan1ItemStateChanged

    private void Tambahan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tambahan1ActionPerformed
       
    }//GEN-LAST:event_Tambahan1ActionPerformed

    private void Tambahan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tambahan2ActionPerformed
        
    }//GEN-LAST:event_Tambahan2ActionPerformed

    private void Tambahan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tambahan3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tambahan3ActionPerformed

    private void Tambahan2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Tambahan2ItemStateChanged
        if(Tambahan2.getText().equals("TV")){
           tv=true;
       }
       if(Tambahan2.getText().equals("Air Panas")){
           airpanas=true;
       }
    }//GEN-LAST:event_Tambahan2ItemStateChanged

    private void Tambahan3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Tambahan3ItemStateChanged
       if(Tambahan3.getText().equals("Air Panas")){
           airpanas=true;
       }
    }//GEN-LAST:event_Tambahan3ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scene2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scene2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scene2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scene2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scene2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BKembali1;
    private javax.swing.JButton BNext1;
    private javax.swing.JLabel LFasilitas1;
    private javax.swing.JLabel LFasilitas2;
    private javax.swing.JLabel LFasilitas3;
    private javax.swing.JLabel LFasilitas4;
    private javax.swing.JLabel LFasilitas5;
    private javax.swing.JLabel LFasilitas6;
    private javax.swing.JLabel Lukuran;
    private javax.swing.JCheckBox Tambahan1;
    private javax.swing.JCheckBox Tambahan2;
    private javax.swing.JCheckBox Tambahan3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel lUkuran;
    // End of variables declaration//GEN-END:variables
}
