

import javax.swing.JComboBox;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author R-PC
 */

public class SceneHarga extends javax.swing.JFrame {
    //Scene1 scene = new Scene1();
    Reguler reg = new Reguler();
    VIP vip1 = new VIP();
    VVIP vvip1 = new VVIP();
    String s;
    static String harga1;
    boolean ac,tv,airpanas;
    static int index,bulan,tahun;
    static String sDate,lamasewa,tgl;
    static String month[]={"Jan","Feb","Mar","Apr","Mei","Jun","Jul","Ags","Sep","Okt","Nov","Des"};
    /**
     * Creates new form SceneHarga
     */
    public SceneHarga() {
        initComponents();
    }
    public SceneHarga(String s,boolean ac,boolean tv,boolean airpanas) {
        initComponents();
        this.s = s;
        reg.setAc(ac);
        reg.setTv(tv);
        reg.tambahan();
        vip1.setAc(ac);
        vip1.setTv(tv);
        vip1.setAirpanas(airpanas);
        vip1.tambahan();
        vvip1.setAc(ac);
        vvip1.setTv(tv);
        vvip1.setAirpanas(airpanas);
        vvip1.tambahan();
        judul.setText("KAMAR  "+s);
        if(s.equals("REGULER")){
            if(ac==true&&tv==true){
                Tambahan1.setText("1. AC (Rp. 200000/bulan)");
                Tambahan2.setText("2. TV (Rp. 100000/bulan)");
            }
            else if(ac==true){
                Tambahan1.setText("1. AC (Rp. 200000/bulan)");
            }
            else if(tv==true){
                Tambahan1.setText("1. TV (Rp. 100000/bulan)");
            }
            else{
                Tambahan1.setText("-");
            }
            cLamaSewa2.setVisible(false);
            cLamaSewa3.setVisible(false);
        }
        else if(s.equals("VIP")){
             if(ac==true&&tv==true&&airpanas==true){
                Tambahan1.setText("1. AC (Rp. 200000/bulan)");
                Tambahan2.setText("2. TV (Rp. 100000/bulan)");
                Tambahan3.setText("3. Air Panas (Rp. 50000/bulan)");
            }
            else if(ac==true&&tv==true){
                Tambahan1.setText("1. AC (Rp. 200000/bulan)");
                Tambahan2.setText("2. TV (Rp. 100000/bulan)");
            }
            else if(ac==true&&airpanas==true){
                Tambahan1.setText("1. AC (Rp. 200000/bulan)");
                Tambahan2.setText("2. Air Panas (Rp. 50000/bulan)");
            }
            else if(tv==true&&airpanas==true){
                Tambahan1.setText("1. TV (Rp. 100000/bulan)");
                Tambahan2.setText("2. Air Panas (Rp. 50000/bulan)");
            }
            else if(ac==true){
                Tambahan1.setText("1. AC (Rp. 200000/bulan)");
            }
            else if(airpanas==true){
                Tambahan1.setText("1. Air Panas (Rp. 50000/bulan)");
            }
            else if(tv==true){
                Tambahan1.setText("1. TV (Rp. 200000/bulan)");
            }
            else{
                Tambahan1.setText("-");
            }
            cLamaSewa.setVisible(false);
            cLamaSewa3.setVisible(false);
        }
        else{
            if(airpanas==true&&tv==true){
                Tambahan1.setText("1. TV (Rp. 100000/bulan)");
                Tambahan2.setText("2. Air Panas (Rp. 50000/bulan)");
            }
            else if(airpanas==true){
                Tambahan1.setText("1. Air Panas (Rp. 50000/bulan)");
            }
            else if(tv==true){
                Tambahan1.setText("1. TV (Rp. 100000/bulan)");
            }
            else{
                Tambahan1.setText("-");
            }
            cLamaSewa2.setVisible(false);
            cLamaSewa.setVisible(false);
        }
        TotalHarga.setText("Rp. 0");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        judul = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cLamaSewa = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        Tambahan1 = new javax.swing.JLabel();
        Tambahan2 = new javax.swing.JLabel();
        Tambahan3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TotalHarga = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        Next = new javax.swing.JButton();
        cLamaSewa2 = new javax.swing.JComboBox();
        cLamaSewa3 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        tgl31 = new javax.swing.JComboBox();
        Bulan = new javax.swing.JComboBox();
        Tahun = new javax.swing.JComboBox();
        tgl30 = new javax.swing.JComboBox();
        tgl29 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("HARGA");

        judul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        judul.setText("KAMAR REGULER");

        jLabel3.setText("Lama Sewa");

        cLamaSewa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3 bulan ( Rp. 1.500.000 )", "6 bulan ( Rp. 3.000.000 )", "12 bulan ( Rp. 5.500.000 )" }));
        cLamaSewa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cLamaSewaItemStateChanged(evt);
            }
        });
        cLamaSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cLamaSewaActionPerformed(evt);
            }
        });

        jLabel2.setText("Tambahan");

        Tambahan1.setText(" ");

        Tambahan2.setText(" ");

        Tambahan3.setText(" ");

        jLabel4.setText("Total Harga");

        TotalHarga.setText("jLabel5");

        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Home.setText("HOME");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        Next.setText("NEXT");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        cLamaSewa2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3 bulan ( Rp. 2.400.000 )", "6 bulan ( Rp. 4.800.000 )", "12 bulan ( Rp. 9.000.000 )" }));
        cLamaSewa2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cLamaSewa2ItemStateChanged(evt);
            }
        });
        cLamaSewa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cLamaSewa2ActionPerformed(evt);
            }
        });

        cLamaSewa3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3 bulan ( Rp. 3.600.000 )", "6 bulan ( Rp. 7.200.000 )", "12 bulan ( Rp. 14.000.000 )" }));
        cLamaSewa3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cLamaSewa3ItemStateChanged(evt);
            }
        });
        cLamaSewa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cLamaSewa3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Mulai Huni");

        tgl31.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        tgl31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl31ActionPerformed(evt);
            }
        });

        Bulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Ags", "Sep", "Okt", "Nov", "Des" }));
        Bulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BulanActionPerformed(evt);
            }
        });

        Tahun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2016", "2017" }));
        Tahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TahunActionPerformed(evt);
            }
        });

        tgl30.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        tgl30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl30ActionPerformed(evt);
            }
        });

        tgl29.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28" }));
        tgl29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl29ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cLamaSewa3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cLamaSewa2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cLamaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(Tambahan2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(Tambahan3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel4)
                        .addGap(44, 44, 44)
                        .addComponent(TotalHarga))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel5)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tgl31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(Back)
                        .addGap(61, 61, 61)
                        .addComponent(Home)
                        .addGap(59, 59, 59)
                        .addComponent(Next))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tambahan1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(judul)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3))
                    .addComponent(cLamaSewa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cLamaSewa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cLamaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Tambahan1))
                .addGap(6, 6, 6)
                .addComponent(Tambahan2)
                .addGap(6, 6, 6)
                .addComponent(Tambahan3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(TotalHarga))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tgl31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tgl30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(tgl29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Back)
                    .addComponent(Home)
                    .addComponent(Next))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cLamaSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cLamaSewaActionPerformed
        JComboBox cb = (JComboBox)evt.getSource();
        String s1 = (String) cb.getSelectedItem();

           if(s1.equals("3 bulan ( Rp. 1.500.000 )")){             
               TotalHarga.setText("Rp. "+reg.harga()+"");
               index =3;
               lamasewa = "3 Bulan";
           }
           else if(s1.equals("6 bulan ( Rp. 3.000.000 )")){
               TotalHarga.setText("Rp. "+reg.harga()*2+"");
               index =6;
               lamasewa = "6 Bulan";
           }
           else{
               TotalHarga.setText("Rp. "+((reg.harga()*4)-500000)+"");
               index =12;
               lamasewa = "12 Bulan";
           }
           harga1 = TotalHarga.getText();
    }//GEN-LAST:event_cLamaSewaActionPerformed

    private void cLamaSewaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cLamaSewaItemStateChanged
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_cLamaSewaItemStateChanged

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        Scene1.scene2.show();
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void cLamaSewa2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cLamaSewa2ItemStateChanged
        
    }//GEN-LAST:event_cLamaSewa2ItemStateChanged

    private void cLamaSewa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cLamaSewa2ActionPerformed
        JComboBox cb = (JComboBox)evt.getSource();
        String s1 = (String) cb.getSelectedItem(); 

            if(s1.equals("3 bulan ( Rp. 2.400.000 )")){
               TotalHarga.setText("Rp. "+vip1.harga()+"");
               index =3;
               lamasewa = "3 Bulan";
           }
           else if(s1.equals("6 bulan ( Rp. 4.800.000 )")){
               TotalHarga.setText("Rp. "+vip1.harga()*2+"");
               index =6;
               lamasewa = "6 Bulan";
           }
           else{
               TotalHarga.setText("Rp. "+((vip1.harga()*4)-600000)+"");
               index =12;
               lamasewa = "12 Bulan";
           }
            harga1 = TotalHarga.getText();
    }//GEN-LAST:event_cLamaSewa2ActionPerformed

    private void cLamaSewa3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cLamaSewa3ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cLamaSewa3ItemStateChanged

    private void cLamaSewa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cLamaSewa3ActionPerformed
        JComboBox cb = (JComboBox)evt.getSource();
        String s1 = (String) cb.getSelectedItem(); 
        
        if(s1.equals("3 bulan ( Rp. 3.600.000 )")){
               TotalHarga.setText("Rp. "+vvip1.harga()+"");
               index =3;
               lamasewa = "3 Bulan";
           }
           else if(s1.equals("6 bulan ( Rp. 7.200.000 )")){
               TotalHarga.setText("Rp. "+vvip1.harga()*2+"");
               index =6;
               lamasewa = "6 Bulan";
           }
           else{
               TotalHarga.setText("Rp. "+((vvip1.harga()*4)-400000)+"");
               index =12;
               lamasewa = "12 Bulan";
           }
        harga1 = TotalHarga.getText();
    }//GEN-LAST:event_cLamaSewa3ActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        new Scene3().show();
        this.dispose();
    }//GEN-LAST:event_NextActionPerformed

    private void tgl31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl31ActionPerformed
        JComboBox cb = (JComboBox)evt.getSource();
        String s1 = (String) cb.getSelectedItem();
        tgl = s1;
    }//GEN-LAST:event_tgl31ActionPerformed
    
    private void BulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BulanActionPerformed
        JComboBox cb = (JComboBox)evt.getSource();
        String s1 = (String) cb.getSelectedItem();
        
        if(s1.equals("Jan")||s1.equals("Mar")||s1.equals("Mei")||s1.equals("Jul")||s1.equals("Ags")||s1.equals("Okt")||s1.equals("Des")){
           int b=0;
            tgl30.setVisible(false);
            tgl29.setVisible(false);
            tgl31.setVisible(true);
            if(s1.equals("Jan")){
                b=1;
            }
            else if(s1.equals("Mar")){
                b=3;
            }
            else if(s1.equals("Mei")){
                b=5;
            }
            else if(s1.equals("Jul")){
                b=7;
            }
            else if(s1.equals("Ags")){
                b=8;
            }
            else if(s1.equals("Okt")){
                b=10;
            }
            else if(s1.equals("Des")){
                b=12;
            }
            bulan=b; 
        }
        else if(s1.equals("Feb")){
            int b =0;
            tgl29.setVisible(true);
            tgl31.setVisible(false);
            tgl30.setVisible(false);
            bulan=b; 
            
        }
        else{
            int b=0;
            tgl30.setVisible(true);
            tgl31.setVisible(false);
            tgl29.setVisible(false);
            if(s1.equals("Apr")){
                b=4;
            }
            else if(s1.equals("Jun")){
                b=6;
            }
            else if(s1.equals("Sep")){
                b=9;
            }
            else if(s1.equals("Nov")){
                b=11;
            }
         bulan=b;   
        }
    }//GEN-LAST:event_BulanActionPerformed

    private void TahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TahunActionPerformed
        JComboBox cb = (JComboBox)evt.getSource();
        String s1 = (String) cb.getSelectedItem();
        int a = Integer.parseInt(s1);
        tahun =a;
    }//GEN-LAST:event_TahunActionPerformed

    private void tgl30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl30ActionPerformed
        JComboBox cb = (JComboBox)evt.getSource();
        String s1 = (String) cb.getSelectedItem();
        tgl=s1;
    }//GEN-LAST:event_tgl30ActionPerformed

    private void tgl29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl29ActionPerformed
        JComboBox cb = (JComboBox)evt.getSource();
        String s1 = (String) cb.getSelectedItem();
        int a = Integer.parseInt(s1);
        tgl=s1;
    }//GEN-LAST:event_tgl29ActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        Scene1.s.show();
        this.dispose();
    }//GEN-LAST:event_HomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SceneHarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SceneHarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SceneHarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SceneHarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SceneHarga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JComboBox Bulan;
    private javax.swing.JButton Home;
    private javax.swing.JButton Next;
    private javax.swing.JComboBox Tahun;
    private javax.swing.JLabel Tambahan1;
    private javax.swing.JLabel Tambahan2;
    private javax.swing.JLabel Tambahan3;
    private javax.swing.JLabel TotalHarga;
    private javax.swing.JComboBox cLamaSewa;
    private javax.swing.JComboBox cLamaSewa2;
    private javax.swing.JComboBox cLamaSewa3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel judul;
    private javax.swing.JComboBox tgl29;
    private javax.swing.JComboBox tgl30;
    private javax.swing.JComboBox tgl31;
    // End of variables declaration//GEN-END:variables
}
